channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=25.0.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - numpy==1.26.1
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
